# Generated by Django 4.2.4 on 2023-08-31 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('announcement', '0002_alter_announcement_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='announcement',
            name='main_image',
            field=models.ImageField(blank=True, upload_to='images/announcement/', verbose_name='фото'),
        ),
    ]
