# Generated by Django 4.2.4 on 2023-09-04 15:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('announcement', '0005_announcement_subcategory'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='announcement',
            options={'ordering': ('created_at',), 'verbose_name': 'Обьявления', 'verbose_name_plural': 'Обьявление'},
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Категории', 'verbose_name_plural': 'Категория'},
        ),
        migrations.AlterModelOptions(
            name='subcategory',
            options={'verbose_name': 'Подкатегории', 'verbose_name_plural': 'Подкатегория'},
        ),
    ]
