# Generated by Django 4.2.4 on 2023-09-04 15:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('announcement', '0006_alter_announcement_options_alter_category_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='announcement',
            options={'ordering': ('created_at',), 'verbose_name': 'Обьявлении', 'verbose_name_plural': 'Обьявления'},
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Категория', 'verbose_name_plural': 'Категории'},
        ),
        migrations.AlterModelOptions(
            name='subcategory',
            options={'verbose_name': 'Подкатегория', 'verbose_name_plural': 'Подкатегории'},
        ),
    ]
